apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: ui
